### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by Gedion-01** [AbdulhakimZ/quantity-picker#3]
i cant even install it

**Comment by AbdulhakimZ** [comment]
What method have you used to install?
Make sure to use the correct package name
`$ yarn add react-qty-picker`

**Comment by Gideon-01** [comment]
I use npm to install.
It says outdated. Update the repo its not compatible with the current
version of react

**Comment by AbdulhakimZ** [comment]
Will work on it. 
Also if you would like to contribute the door is open for open source contributors.

**Comment by Gedion-01** [comment]
Thanks, I will.
